"""
PACCS Filmmaker Intelligence Report Generator
Creates professional PDF reports for each film
"""
from datetime import datetime
import json

class FilmReportGenerator:
    """Generates comprehensive intelligence reports for filmmakers"""
    
    def __init__(self):
        self.report_template = """
╔══════════════════════════════════════════════════════════════════╗
║                 PACCS FILM INTELLIGENCE REPORT                   ║
║          Peekaboon Agentic Creative Curation System              ║
╠══════════════════════════════════════════════════════════════════╣
║  Generated: {timestamp}                                          
╚══════════════════════════════════════════════════════════════════╝

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                         FILM DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Title:      {title}
  Director:   {director}
  Country:    {country}
  Duration:   {duration} minutes
  Genre:      {genre}
  Themes:     {themes}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                       PACCS SCORES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ┌─────────────────────────────────────────────────────────┐
  │                                                         │
  │   OVERALL PACCS SCORE:  {final_score}/10               │
  │   Confidence Level:      {confidence}%                  │
  │                                                         │
  │   Quality Score:         {quality_score}/10            │
  │   Market Score:          {market_score}/10             │
  │                                                         │
  │   Recommended Pathway:   {pathway}                     │
  │                                                         │
  └─────────────────────────────────────────────────────────┘

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                    QUALITY ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Strengths:
{strengths}

  Areas for Development:
{improvements}

  Predictive Factors:
{predictive_factors}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                    MARKET ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Genre Trend:        {genre_trend}
  Target Audiences:   {target_audiences}
  
  Recommended Platforms:
{platforms}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                 TOP FESTIVAL MATCHES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{festival_matches}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                TOP DISTRIBUTOR MATCHES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{distributor_matches}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                 RECOMMENDED NEXT STEPS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{next_steps}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                    FESTIVAL STRATEGY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{festival_strategy}

══════════════════════════════════════════════════════════════════
                         DISCLAIMER
══════════════════════════════════════════════════════════════════

This report is generated by PACCS (Peekaboon Agentic Creative 
Curation System) using AI-powered multi-agent analysis. Scores 
and recommendations are based on pattern recognition from 
historical festival data and should be used as guidance only.

Final creative and business decisions should be made in 
consultation with industry professionals.

Report ID: {report_id}
© {year} PAHUS Studios Limited - All Rights Reserved

══════════════════════════════════════════════════════════════════
"""
    
    def generate_report(self, film, quality_result, market_result, routing_result):
        """Generate a complete intelligence report for a film"""
        
        # Format strengths
        strengths = quality_result.get('strengths', [])
        strengths_text = "\n".join([f"    ✓ {s}" for s in strengths]) if strengths else "    • Analysis in progress"
        
        # Format improvements
        improvements = quality_result.get('improvements', [])
        improvements_text = "\n".join([f"    → {i}" for i in improvements]) if improvements else "    • No major areas identified"
        
        # Format predictive factors
        predictive = quality_result.get('predictive_adjustments', [])
        predictive_text = "\n".join([f"    ★ {p}" for p in predictive[:5]]) if predictive else "    • Standard analysis applied"
        
        # Format platforms
        platforms = market_result.get('recommended_platforms', [])
        platforms_text = "\n".join([f"    • {p}" for p in platforms]) if platforms else "    • General distribution"
        
        # Format festival matches
        festivals = routing_result.get('festival_matches', [])
        if festivals:
            festival_lines = []
            for i, f in enumerate(festivals[:5], 1):
                festival_lines.append(f"  {i}. {f['name']}")
                festival_lines.append(f"     Country: {f['country']} | Match: {f['match_score']}%")
                festival_lines.append(f"     Tier: {f['tier']} | Prestige: {f['prestige']}/10")
                festival_lines.append("")
            festival_text = "\n".join(festival_lines)
        else:
            festival_text = "  No strong festival matches found.\n  Consider building festival history with regional events."
        
        # Format distributor matches
        distributors = market_result.get('distributor_matches', [])
        if distributors:
            dist_lines = []
            for i, d in enumerate(distributors[:5], 1):
                dist_lines.append(f"  {i}. {d['name']}")
                dist_lines.append(f"     Match Score: {d['match_score']}%")
                dist_lines.append(f"     Territories: {', '.join(d['territories'])}")
                dist_lines.append("")
            distributor_text = "\n".join(dist_lines)
        else:
            distributor_text = "  Building quality score will unlock distributor matches."
        
        # Format next steps
        steps = routing_result.get('next_steps', [])
        steps_text = "\n".join([f"  {i}. {s}" for i, s in enumerate(steps, 1)]) if steps else "  1. Continue building festival presence"
        
        # Format festival strategy
        strategy = routing_result.get('festival_strategy', [])
        strategy_text = "\n".join([f"  → {s}" for s in strategy]) if strategy else "  → Focus on regional festivals first"
        
        # Fill template
        report = self.report_template.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            title=film.get('title', 'Unknown'),
            director=film.get('director', 'Unknown'),
            country=film.get('country', 'Unknown'),
            duration=film.get('duration_minutes', 'N/A'),
            genre=film.get('genre', 'General'),
            themes=", ".join(film.get('themes', ['General'])),
            final_score=routing_result.get('final_score', 
                round((quality_result['score'] + market_result['score']) / 2, 1)),
            confidence=int(routing_result.get('confidence', 0.7) * 100),
            quality_score=quality_result.get('score', 'N/A'),
            market_score=market_result.get('score', 'N/A'),
            pathway=routing_result.get('primary_pathway', 'FESTIVAL'),
            strengths=strengths_text,
            improvements=improvements_text,
            predictive_factors=predictive_text,
            genre_trend=market_result.get('genre_trend', 'stable').upper(),
            target_audiences=", ".join(market_result.get('target_audiences', ['General'])),
            platforms=platforms_text,
            festival_matches=festival_text,
            distributor_matches=distributor_text,
            next_steps=steps_text,
            festival_strategy=strategy_text,
            report_id=f"PACCS-{film.get('id', 'XXX')}-{datetime.now().strftime('%Y%m%d')}",
            year=datetime.now().year
        )
        
        return report
    
    def save_report(self, report, filename):
        """Save report to text file"""
        with open(filename, 'w') as f:
            f.write(report)
        print(f"Report saved to: {filename}")
        return filename
    
    def generate_html_report(self, film, quality_result, market_result, routing_result):
        """Generate HTML version of the report for web display"""
        
        festivals = routing_result.get('festival_matches', [])
        distributors = market_result.get('distributor_matches', [])
        
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>PACCS Report - {film.get('title', 'Film')}</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        .report {{ background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .header {{ text-align: center; border-bottom: 3px solid #1a365d; padding-bottom: 20px; margin-bottom: 20px; }}
        .header h1 {{ color: #1a365d; margin: 0; }}
        .header p {{ color: #666; }}
        .score-box {{ background: #1a365d; color: white; padding: 20px; border-radius: 10px; text-align: center; margin: 20px 0; }}
        .score-box .big-score {{ font-size: 48px; font-weight: bold; }}
        .score-box .pathway {{ font-size: 24px; color: #90cdf4; }}
        .section {{ margin: 25px 0; padding: 15px; background: #f8fafc; border-radius: 8px; }}
        .section h2 {{ color: #1a365d; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }}
        .match-card {{ background: white; padding: 15px; margin: 10px 0; border-radius: 8px; border-left: 4px solid #2c5282; }}
        .match-score {{ float: right; background: #2c5282; color: white; padding: 5px 10px; border-radius: 20px; }}
        ul {{ list-style-type: none; padding-left: 0; }}
        li {{ padding: 8px 0; border-bottom: 1px solid #eee; }}
        li:before {{ content: "→ "; color: #2c5282; font-weight: bold; }}
        .footer {{ text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="report">
        <div class="header">
            <h1>PACCS Film Intelligence Report</h1>
            <p>Peekaboon Agentic Creative Curation System</p>
        </div>
        
        <h2>{film.get('title', 'Unknown Film')}</h2>
        <p><strong>Director:</strong> {film.get('director', 'Unknown')} | 
           <strong>Country:</strong> {film.get('country', 'Unknown')} | 
           <strong>Duration:</strong> {film.get('duration_minutes', 'N/A')} min</p>
        
        <div class="score-box">
            <div class="big-score">{round((quality_result['score'] + market_result['score']) / 2, 1)}/10</div>
            <div>PACCS Score</div>
            <div class="pathway">{routing_result.get('primary_pathway', 'FESTIVAL')}</div>
            <div>Recommended Pathway</div>
        </div>
        
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
            <div class="section">
                <h3>Quality Score: {quality_result['score']}/10</h3>
                <p>Confidence: {int(quality_result['confidence'] * 100)}%</p>
            </div>
            <div class="section">
                <h3>Market Score: {market_result['score']}/10</h3>
                <p>Trend: {market_result.get('genre_trend', 'stable').upper()}</p>
            </div>
        </div>
        
        <div class="section">
            <h2>Top Festival Matches</h2>
            {"".join([f'<div class="match-card"><span class="match-score">{f["match_score"]}%</span><strong>{f["name"]}</strong><br><small>{f["country"]} | Tier {f["tier"]}</small></div>' for f in festivals[:5]]) if festivals else '<p>Building quality score will unlock festival matches.</p>'}
        </div>
        
        <div class="section">
            <h2>Distributor Matches</h2>
            {"".join([f'<div class="match-card"><span class="match-score">{d["match_score"]}%</span><strong>{d["name"]}</strong><br><small>{", ".join(d["territories"])}</small></div>' for d in distributors[:5]]) if distributors else '<p>Continue building to unlock distributor matches.</p>'}
        </div>
        
        <div class="section">
            <h2>Recommended Next Steps</h2>
            <ul>
                {"".join([f'<li>{step}</li>' for step in routing_result.get('next_steps', ['Continue building festival presence'])])}
            </ul>
        </div>
        
        <div class="footer">
            <p>Report ID: PACCS-{film.get('id', 'XXX')}-{datetime.now().strftime('%Y%m%d')}</p>
            <p>© {datetime.now().year} PAHUS Studios Limited - All Rights Reserved</p>
            <p><em>This report is AI-generated guidance. Consult industry professionals for final decisions.</em></p>
        </div>
    </div>
</body>
</html>
"""
        return html


# Test the report generator
if __name__ == "__main__":
    print("="*60)
    print("PACCS Report Generator Test")
    print("="*60)
    
    # Mock data for testing
    test_film = {
        "id": "FILM_0001",
        "title": "Breaking Silence",
        "director": "Priya Sharma",
        "country": "India",
        "duration_minutes": 52,
        "genre": "Documentary",
        "themes": ["Mental Health", "Social Justice"]
    }
    
    test_quality = {
        "score": 7.8,
        "confidence": 0.85,
        "strengths": ["Strong technical execution", "Compelling narrative"],
        "improvements": ["Consider tighter edit"],
        "predictive_adjustments": ["Trending themes: Mental Health", "Strong film culture origin"]
    }
    
    test_market = {
        "score": 7.5,
        "confidence": 0.80,
        "genre_trend": "rising",
        "target_audiences": ["Documentary enthusiasts", "Social impact audiences"],
        "recommended_platforms": ["Netflix", "HBO", "BBC"],
        "distributor_matches": [
            {"name": "Netflix Documentary", "match_score": 85, "territories": ["Global"]},
            {"name": "BBC Storyville", "match_score": 78, "territories": ["UK", "Global"]}
        ]
    }
    
    test_routing = {
        "primary_pathway": "FESTIVAL",
        "confidence": 0.82,
        "next_steps": [
            "Submit to IDFA Amsterdam",
            "Prepare press kit",
            "Contact impact distribution partners"
        ],
        "festival_matches": [
            {"name": "IDFA Amsterdam", "country": "Netherlands", "tier": 1, "match_score": 88, "prestige": 9},
            {"name": "Hot Docs", "country": "Canada", "tier": 2, "match_score": 82, "prestige": 8},
            {"name": "Sheffield DocFest", "country": "UK", "tier": 2, "match_score": 75, "prestige": 7}
        ],
        "festival_strategy": ["Aim high: Submit to IDFA first", "Backup: Hot Docs"]
    }
    
    generator = FilmReportGenerator()
    
    # Generate text report
    report = generator.generate_report(test_film, test_quality, test_market, test_routing)
    print("\n" + report)
    
    # Save report
    generator.save_report(report, "test_report.txt")
    
    # Generate HTML report
    html_report = generator.generate_html_report(test_film, test_quality, test_market, test_routing)
    with open("test_report.html", "w") as f:
        f.write(html_report)
    print("\nHTML report saved to: test_report.html")
    
    print("\n" + "="*60)
    print("Report generator test complete!")